# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test:ci > client-coverage-console-output.txt
    - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
      with:
        coverage-summary-path: ./__coverage__/coverage-final.json
        coverage-path: client-coverage-console-output.txt
        title: Front-end Code Coverage
        summary-title: Summary
        coverage-title: Report
        badge-title: Coverage
        hide-comment: false
        create-new-comment: false
        hide-summary: false
        # optimizations to reduce space on PR comment
        remove-links-to-files: true
        remove-links-to-lines: true
        report-only-changed-files: true
